### ISSUE TITLE
Does `lstautogobble` work with `\lstinputlisting`?

### ISSUE THREAD

**Issue by SamWilsn** [MartinScharrer/lstaddons#4]
Sorry if this has been answered elsewhere, but I'm trying to use something like:

```latex
\lstinputlisting[autogobble=true,firstline=40,lastline=47]{foo.rs}
```

**Comment by mbertucci47** [comment]
@SamWilsn Well `gobble` doesn't work with `\lstinputlisting` (see the listings doc or [this](https://tex.stackexchange.com/q/83340/208544) TeX-SX question) so I doubt `autogobble` is intended to work with it
